# Generated by Django 3.0.4 on 2020-04-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='book_name',
            new_name='association_name',
        ),
    ]
