# Generated by Django 3.0.4 on 2020-04-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_auto_20200411_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='count',
            new_name='vote',
        ),
    ]
